spring:
  application:
    name: demoUser

  datasource:
    url: jdbc:postgresql://localhost:5433/mydb
    username: postgres
    password: Molir1
    #driver
    #hikari just to know

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#loging level debug
  main:
    web-application-type: servlet

